name: techcase1
description: "A new Flutter project."
publish_to: 'none'  # Don't publish this package to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.6.2 <4.0.0"  # Ensures the app runs only on SDK version 3.6.2 or later

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  just_audio: ^0.9.36  # For audio playback
  video_player: ^2.7.2  # For video playback
  audio_service: ^0.18.12  # For handling background audio and interruptions
  permission_handler: ^11.0.1  # For permission handling
  audioplayers: ^6.2.0  # Optional, for alternative audio playback

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true  # Use Material Design components
  assets:
    - android/app/assets/images/  # Correct path for images
    - android/app/assets/sound/   # Correct path for sound
